/**********************************************************************************
Copyright (c) 2003, Albert M. Choy
All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer in the documentation
      and/or other materials provided with the distribution.
    * Neither the name of Microplanet, Inc. nor the names of its contributors
      may be used to endorse or promote products derived from this software
      without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
**********************************************************************************/





//Name: iso-8859-13
//Description: Latin7: Baltic Rim
//Version: 1
//Charset: ISO-8859-13, ISO_8859-13, latin7, l7, csISOLatin7

#include "stdafx.h"
#include "8859-13.h"

WCHAR vwc8859_13[128];


void  init_8859_13()
   {
   // fill in  0x80  to 0xFF
   const int k = 0x80;

   // fill with invalid char
   for (int j = 0; j < 128; j++)
      vwc8859_13[128] = 0;

   // shorthand
   WCHAR * p = &vwc8859_13[0];

p[0xA0-k] =	0x00A0;	//#	NO-BREAK SPACE
p[0xA1-k] =	0x201D;	//#	RIGHT DOUBLE QUOTATION MARK
p[0xA2-k] =	0x00A2;	//#	CENT SIGN
p[0xA3-k] =	0x00A3;	//#	POUND SIGN
p[0xA4-k] =	0x00A4;	//#	CURRENCY SIGN
p[0xA5-k] =	0x201E;	//#	DOUBLE LOW-9 QUOTATION MARK
p[0xA6-k] =	0x00A6;	//#	BROKEN BAR
p[0xA7-k] =	0x00A7;	//#	SECTION SIGN
p[0xA8-k] =	0x00D8;	//#	LATIN CAPITAL LETTER O WITH STROKE
p[0xA9-k] =	0x00A9;	//#	COPYRIGHT SIGN
p[0xAA-k] =	0x0156;	//#	LATIN CAPITAL LETTER R WITH CEDILLA
p[0xAB-k] =	0x00AB;	//#	LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
p[0xAC-k] =	0x00AC;	//#	NOT SIGN
p[0xAD-k] =	0x00AD;	//#	SOFT HYPHEN
p[0xAE-k] =	0x00AE;	//#	REGISTERED SIGN
p[0xAF-k] =	0x00C6;	//#	LATIN CAPITAL LETTER AE
p[0xB0-k] =	0x00B0;	//#	DEGREE SIGN
p[0xB1-k] =	0x00B1;	//#	PLUS-MINUS SIGN
p[0xB2-k] =	0x00B2;	//#	SUPERSCRIPT TWO
p[0xB3-k] =	0x00B3;	//#	SUPERSCRIPT THREE
p[0xB4-k] =	0x201C;	//#	LEFT DOUBLE QUOTATION MARK
p[0xB5-k] =	0x00B5;	//#	MICRO SIGN
p[0xB6-k] =	0x00B6;	//#	PILCROW SIGN
p[0xB7-k] =	0x00B7;	//#	MIDDLE DOT
p[0xB8-k] =	0x00F8;	//#	LATIN SMALL LETTER O WITH STROKE
p[0xB9-k] =	0x00B9;	//#	SUPERSCRIPT ONE
p[0xBA-k] =	0x0157;	//#	LATIN SMALL LETTER R WITH CEDILLA
p[0xBB-k] =	0x00BB;	//#	RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
p[0xBC-k] =	0x00BC;	//#	VULGAR FRACTION ONE QUARTER
p[0xBD-k] =	0x00BD;	//#	VULGAR FRACTION ONE HALF
p[0xBE-k] =	0x00BE;	//#	VULGAR FRACTION THREE QUARTERS
p[0xBF-k] =	0x00E6;	//#	LATIN SMALL LETTER AE
p[0xC0-k] =	0x0104;	//#	LATIN CAPITAL LETTER A WITH OGONEK
p[0xC1-k] =	0x012E;	//#	LATIN CAPITAL LETTER I WITH OGONEK
p[0xC2-k] =	0x0100;	//#	LATIN CAPITAL LETTER A WITH MACRON
p[0xC3-k] =	0x0106;	//#	LATIN CAPITAL LETTER C WITH ACUTE
p[0xC4-k] =	0x00C4;	//#	LATIN CAPITAL LETTER A WITH DIAERESIS
p[0xC5-k] =	0x00C5;	//#	LATIN CAPITAL LETTER A WITH RING ABOVE
p[0xC6-k] =	0x0118;	//#	LATIN CAPITAL LETTER E WITH OGONEK
p[0xC7-k] =	0x0112;	//#	LATIN CAPITAL LETTER E WITH MACRON
p[0xC8-k] =	0x010C;	//#	LATIN CAPITAL LETTER C WITH CARON
p[0xC9-k] =	0x00C9;	//#	LATIN CAPITAL LETTER E WITH ACUTE
p[0xCA-k] =	0x0179;	//#	LATIN CAPITAL LETTER Z WITH ACUTE
p[0xCB-k] =	0x0116;	//#	LATIN CAPITAL LETTER E WITH DOT ABOVE
p[0xCC-k] =	0x0122;	//#	LATIN CAPITAL LETTER G WITH CEDILLA
p[0xCD-k] =	0x0136;	//#	LATIN CAPITAL LETTER K WITH CEDILLA
p[0xCE-k] =	0x012A;	//#	LATIN CAPITAL LETTER I WITH MACRON
p[0xCF-k] =	0x013B;	//#	LATIN CAPITAL LETTER L WITH CEDILLA
p[0xD0-k] =	0x0160;	//#	LATIN CAPITAL LETTER S WITH CARON
p[0xD1-k] =	0x0143;	//#	LATIN CAPITAL LETTER N WITH ACUTE
p[0xD2-k] =	0x0145;	//#	LATIN CAPITAL LETTER N WITH CEDILLA
p[0xD3-k] =	0x00D3;	//#	LATIN CAPITAL LETTER O WITH ACUTE
p[0xD4-k] =	0x014C;	//#	LATIN CAPITAL LETTER O WITH MACRON
p[0xD5-k] =	0x00D5;	//#	LATIN CAPITAL LETTER O WITH TILDE
p[0xD6-k] =	0x00D6;	//#	LATIN CAPITAL LETTER O WITH DIAERESIS
p[0xD7-k] =	0x00D7;	//#	MULTIPLICATION SIGN
p[0xD8-k] =	0x0172;	//#	LATIN CAPITAL LETTER U WITH OGONEK
p[0xD9-k] =	0x0141;	//#	LATIN CAPITAL LETTER L WITH STROKE
p[0xDA-k] =	0x015A;	//#	LATIN CAPITAL LETTER S WITH ACUTE
p[0xDB-k] =	0x016A;	//#	LATIN CAPITAL LETTER U WITH MACRON
p[0xDC-k] =	0x00DC;	//#	LATIN CAPITAL LETTER U WITH DIAERESIS
p[0xDD-k] =	0x017B;	//#	LATIN CAPITAL LETTER Z WITH DOT ABOVE
p[0xDE-k] =	0x017D;	//#	LATIN CAPITAL LETTER Z WITH CARON
p[0xDF-k] =	0x00DF;	//#	LATIN SMALL LETTER SHARP S
p[0xE0-k] =	0x0105;	//#	LATIN SMALL LETTER A WITH OGONEK
p[0xE1-k] =	0x012F;	//#	LATIN SMALL LETTER I WITH OGONEK
p[0xE2-k] =	0x0101;	//#	LATIN SMALL LETTER A WITH MACRON
p[0xE3-k] =	0x0107;	//#	LATIN SMALL LETTER C WITH ACUTE
p[0xE4-k] =	0x00E4;	//#	LATIN SMALL LETTER A WITH DIAERESIS
p[0xE5-k] =	0x00E5;	//#	LATIN SMALL LETTER A WITH RING ABOVE
p[0xE6-k] =	0x0119;	//#	LATIN SMALL LETTER E WITH OGONEK
p[0xE7-k] =	0x0113;	//#	LATIN SMALL LETTER E WITH MACRON
p[0xE8-k] =	0x010D;	//#	LATIN SMALL LETTER C WITH CARON
p[0xE9-k] =	0x00E9;	//#	LATIN SMALL LETTER E WITH ACUTE
p[0xEA-k] =	0x017A;	//#	LATIN SMALL LETTER Z WITH ACUTE
p[0xEB-k] =	0x0117;	//#	LATIN SMALL LETTER E WITH DOT ABOVE
p[0xEC-k] =	0x0123;	//#	LATIN SMALL LETTER G WITH CEDILLA
p[0xED-k] =	0x0137;	//#	LATIN SMALL LETTER K WITH CEDILLA
p[0xEE-k] =	0x012B;	//#	LATIN SMALL LETTER I WITH MACRON
p[0xEF-k] =	0x013C;	//#	LATIN SMALL LETTER L WITH CEDILLA
p[0xF0-k] =	0x0161;	//#	LATIN SMALL LETTER S WITH CARON
p[0xF1-k] =	0x0144;	//#	LATIN SMALL LETTER N WITH ACUTE
p[0xF2-k] =	0x0146;	//#	LATIN SMALL LETTER N WITH CEDILLA
p[0xF3-k] =	0x00F3;	//#	LATIN SMALL LETTER O WITH ACUTE
p[0xF4-k] =	0x014D;	//#	LATIN SMALL LETTER O WITH MACRON
p[0xF5-k] =	0x00F5;	//#	LATIN SMALL LETTER O WITH TILDE
p[0xF6-k] =	0x00F6;	//#	LATIN SMALL LETTER O WITH DIAERESIS
p[0xF7-k] =	0x00F7;	//#	DIVISION SIGN
p[0xF8-k] =	0x0173;	//#	LATIN SMALL LETTER U WITH OGONEK
p[0xF9-k] =	0x0142;	//#	LATIN SMALL LETTER L WITH STROKE
p[0xFA-k] =	0x015B;	//#	LATIN SMALL LETTER S WITH ACUTE
p[0xFB-k] =	0x016B;	//#	LATIN SMALL LETTER U WITH MACRON
p[0xFC-k] =	0x00FC;	//#	LATIN SMALL LETTER U WITH DIAERESIS
p[0xFD-k] =	0x017C;	//#	LATIN SMALL LETTER Z WITH DOT ABOVE
p[0xFE-k] =	0x017E;	//#	LATIN SMALL LETTER Z WITH CARON
p[0xFF-k] =	0x00B4;	//#	ACUTE ACCENT
}