/**********************************************************************************
Copyright (c) 2003, Albert M. Choy
All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer in the documentation
      and/or other materials provided with the distribution.
    * Neither the name of Microplanet, Inc. nor the names of its contributors
      may be used to endorse or promote products derived from this software
      without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
**********************************************************************************/





//Name: iso-8859-14
//Description: Latin8: Celtic
//Version: 1
//Charset: ISO-8859-14, ISO_8859-14, latin8, l8, csISOLatin8

#include "stdafx.h"
#include "8859-14.h"

WCHAR vwc8859_14[128];


void  init_8859_14()
   {
   // fill in  0x80  to 0xFF
   const int k = 0x80;

   // fill with invalid char
   for (int j = 0; j < 128; j++)
      vwc8859_14[128] = 0;

   // shorthand
   WCHAR * p = &vwc8859_14[0];

p[0xA0-k] =	0x00A0;	//#	NO-BREAK SPACE
p[0xA1-k] =	0x1E02;	//#	LATIN CAPITAL LETTER B WITH DOT ABOVE
p[0xA2-k] =	0x1E03;	//#	LATIN SMALL LETTER B WITH DOT ABOVE
p[0xA3-k] =	0x00A3;	//#	POUND SIGN
p[0xA4-k] =	0x010A;	//#	LATIN CAPITAL LETTER C WITH DOT ABOVE
p[0xA5-k] =	0x010B;	//#	LATIN SMALL LETTER C WITH DOT ABOVE
p[0xA6-k] =	0x1E0A;	//#	LATIN CAPITAL LETTER D WITH DOT ABOVE
p[0xA7-k] =	0x00A7;	//#	SECTION SIGN
p[0xA8-k] =	0x1E80;	//#	LATIN CAPITAL LETTER W WITH GRAVE
p[0xA9-k] =	0x00A9;	//#	COPYRIGHT SIGN
p[0xAA-k] =	0x1E82;	//#	LATIN CAPITAL LETTER W WITH ACUTE
p[0xAB-k] =	0x1E0B;	//#	LATIN SMALL LETTER D WITH DOT ABOVE
p[0xAC-k] =	0x1EF2;	//#	LATIN CAPITAL LETTER Y WITH GRAVE
p[0xAD-k] =	0x00AD;	//#	SOFT HYPHEN
p[0xAE-k] =	0x00AE;	//#	REGISTERED SIGN
p[0xAF-k] =	0x0178;	//#	LATIN CAPITAL LETTER Y WITH DIAERESIS
p[0xB0-k] =	0x1E1E;	//#	LATIN CAPITAL LETTER F WITH DOT ABOVE
p[0xB1-k] =	0x1E1F;	//#	LATIN SMALL LETTER F WITH DOT ABOVE
p[0xB2-k] =	0x0120;	//#	LATIN CAPITAL LETTER G WITH DOT ABOVE
p[0xB3-k] =	0x0121;	//#	LATIN SMALL LETTER G WITH DOT ABOVE
p[0xB4-k] =	0x1E40;	//#	LATIN CAPITAL LETTER M WITH DOT ABOVE
p[0xB5-k] =	0x1E41;	//#	LATIN SMALL LETTER M WITH DOT ABOVE
p[0xB6-k] =	0x00B6;	//#	PILCROW SIGN
p[0xB7-k] =	0x1E56;	//#	LATIN CAPITAL LETTER P WITH DOT ABOVE
p[0xB8-k] =	0x1E81;	//#	LATIN SMALL LETTER W WITH GRAVE
p[0xB9-k] =	0x1E57;	//#	LATIN SMALL LETTER P WITH DOT ABOVE
p[0xBA-k] =	0x1E83;	//#	LATIN SMALL LETTER W WITH ACUTE
p[0xBB-k] =	0x1E60;	//#	LATIN CAPITAL LETTER S WITH DOT ABOVE
p[0xBC-k] =	0x1EF3;	//#	LATIN SMALL LETTER Y WITH GRAVE
p[0xBD-k] =	0x1E84;	//#	LATIN CAPITAL LETTER W WITH DIAERESIS
p[0xBE-k] =	0x1E85;	//#	LATIN SMALL LETTER W WITH DIAERESIS
p[0xBF-k] =	0x1E61;	//#	LATIN SMALL LETTER S WITH DOT ABOVE
p[0xC0-k] =	0x00C0;	//#	LATIN CAPITAL LETTER A WITH GRAVE
p[0xC1-k] =	0x00C1;	//#	LATIN CAPITAL LETTER A WITH ACUTE
p[0xC2-k] =	0x00C2;	//#	LATIN CAPITAL LETTER A WITH CIRCUMFLEX
p[0xC3-k] =	0x00C3;	//#	LATIN CAPITAL LETTER A WITH TILDE
p[0xC4-k] =	0x00C4;	//#	LATIN CAPITAL LETTER A WITH DIAERESIS
p[0xC5-k] =	0x00C5;	//#	LATIN CAPITAL LETTER A WITH RING ABOVE
p[0xC6-k] =	0x00C6;	//#	LATIN CAPITAL LETTER AE
p[0xC7-k] =	0x00C7;	//#	LATIN CAPITAL LETTER C WITH CEDILLA
p[0xC8-k] =	0x00C8;	//#	LATIN CAPITAL LETTER E WITH GRAVE
p[0xC9-k] =	0x00C9;	//#	LATIN CAPITAL LETTER E WITH ACUTE
p[0xCA-k] =	0x00CA;	//#	LATIN CAPITAL LETTER E WITH CIRCUMFLEX
p[0xCB-k] =	0x00CB;	//#	LATIN CAPITAL LETTER E WITH DIAERESIS
p[0xCC-k] =	0x00CC;	//#	LATIN CAPITAL LETTER I WITH GRAVE
p[0xCD-k] =	0x00CD;	//#	LATIN CAPITAL LETTER I WITH ACUTE
p[0xCE-k] =	0x00CE;	//#	LATIN CAPITAL LETTER I WITH CIRCUMFLEX
p[0xCF-k] =	0x00CF;	//#	LATIN CAPITAL LETTER I WITH DIAERESIS
p[0xD0-k] =	0x0174;	//#	LATIN CAPITAL LETTER W WITH CIRCUMFLEX
p[0xD1-k] =	0x00D1;	//#	LATIN CAPITAL LETTER N WITH TILDE
p[0xD2-k] =	0x00D2;	//#	LATIN CAPITAL LETTER O WITH GRAVE
p[0xD3-k] =	0x00D3;	//#	LATIN CAPITAL LETTER O WITH ACUTE
p[0xD4-k] =	0x00D4;	//#	LATIN CAPITAL LETTER O WITH CIRCUMFLEX
p[0xD5-k] =	0x00D5;	//#	LATIN CAPITAL LETTER O WITH TILDE
p[0xD6-k] =	0x00D6;	//#	LATIN CAPITAL LETTER O WITH DIAERESIS
p[0xD7-k] =	0x1E6A;	//#	LATIN CAPITAL LETTER T WITH DOT ABOVE
p[0xD8-k] =	0x00D8;	//#	LATIN CAPITAL LETTER O WITH STROKE
p[0xD9-k] =	0x00D9;	//#	LATIN CAPITAL LETTER U WITH GRAVE
p[0xDA-k] =	0x00DA;	//#	LATIN CAPITAL LETTER U WITH ACUTE
p[0xDB-k] =	0x00DB;	//#	LATIN CAPITAL LETTER U WITH CIRCUMFLEX
p[0xDC-k] =	0x00DC;	//#	LATIN CAPITAL LETTER U WITH DIAERESIS
p[0xDD-k] =	0x00DD;	//#	LATIN CAPITAL LETTER Y WITH ACUTE
p[0xDE-k] =	0x0176;	//#	LATIN CAPITAL LETTER Y WITH CIRCUMFLEX
p[0xDF-k] =	0x00DF;	//#	LATIN SMALL LETTER SHARP S
p[0xE0-k] =	0x00E0;	//#	LATIN SMALL LETTER A WITH GRAVE
p[0xE1-k] =	0x00E1;	//#	LATIN SMALL LETTER A WITH ACUTE
p[0xE2-k] =	0x00E2;	//#	LATIN SMALL LETTER A WITH CIRCUMFLEX
p[0xE3-k] =	0x00E3;	//#	LATIN SMALL LETTER A WITH TILDE
p[0xE4-k] =	0x00E4;	//#	LATIN SMALL LETTER A WITH DIAERESIS
p[0xE5-k] =	0x00E5;	//#	LATIN SMALL LETTER A WITH RING ABOVE
p[0xE6-k] =	0x00E6;	//#	LATIN SMALL LETTER AE
p[0xE7-k] =	0x00E7;	//#	LATIN SMALL LETTER C WITH CEDILLA
p[0xE8-k] =	0x00E8;	//#	LATIN SMALL LETTER E WITH GRAVE
p[0xE9-k] =	0x00E9;	//#	LATIN SMALL LETTER E WITH ACUTE
p[0xEA-k] =	0x00EA;	//#	LATIN SMALL LETTER E WITH CIRCUMFLEX
p[0xEB-k] =	0x00EB;	//#	LATIN SMALL LETTER E WITH DIAERESIS
p[0xEC-k] =	0x00EC;	//#	LATIN SMALL LETTER I WITH GRAVE
p[0xED-k] =	0x00ED;	//#	LATIN SMALL LETTER I WITH ACUTE
p[0xEE-k] =	0x00EE;	//#	LATIN SMALL LETTER I WITH CIRCUMFLEX
p[0xEF-k] =	0x00EF;	//#	LATIN SMALL LETTER I WITH DIAERESIS
p[0xF0-k] =	0x0175;	//#	LATIN SMALL LETTER W WITH CIRCUMFLEX
p[0xF1-k] =	0x00F1;	//#	LATIN SMALL LETTER N WITH TILDE
p[0xF2-k] =	0x00F2;	//#	LATIN SMALL LETTER O WITH GRAVE
p[0xF3-k] =	0x00F3;	//#	LATIN SMALL LETTER O WITH ACUTE
p[0xF4-k] =	0x00F4;	//#	LATIN SMALL LETTER O WITH CIRCUMFLEX
p[0xF5-k] =	0x00F5;	//#	LATIN SMALL LETTER O WITH TILDE
p[0xF6-k] =	0x00F6;	//#	LATIN SMALL LETTER O WITH DIAERESIS
p[0xF7-k] =	0x1E6B;	//#	LATIN SMALL LETTER T WITH DOT ABOVE
p[0xF8-k] =	0x00F8;	//#	LATIN SMALL LETTER O WITH STROKE
p[0xF9-k] =	0x00F9;	//#	LATIN SMALL LETTER U WITH GRAVE
p[0xFA-k] =	0x00FA;	//#	LATIN SMALL LETTER U WITH ACUTE
p[0xFB-k] =	0x00FB;	//#	LATIN SMALL LETTER U WITH CIRCUMFLEX
p[0xFC-k] =	0x00FC;	//#	LATIN SMALL LETTER U WITH DIAERESIS
p[0xFD-k] =	0x00FD;	//#	LATIN SMALL LETTER Y WITH ACUTE
p[0xFE-k] =	0x0177;	//#	LATIN SMALL LETTER Y WITH CIRCUMFLEX
p[0xFF-k] =	0x00FF;	//#	LATIN SMALL LETTER Y WITH DIAERESIS
}